turns = {
1: "CRO insists sales and finance share one win definition versus recognized revenue and cash, with concessions modeled not hidden. RevOps must tie lagging funnel stats to pipeline coverage by segment. PMM and CS must surface sell-vs-deliver gaps so pay does not reward deals onboarding cannot absorb. AE and SE ramp realism, large-deal cycle stretch, and discount multiyear limits must protect net-new.",
2: "CFO ties wins to collectibility and revenue rules, not ink. Deal bends must hit concession economics before margin breaks under heavy delivery on giants. Segment and vintage tracking shows billings drift, deferred buildup, slow pay versus headline pipeline. Gates: margin-after-delivery floors, discount and term caps, multiyear mix with net-new floors so volume is not traded for stretched cash.",
3: "RevOps will gate CRM and quoting so closed-won waits on modeled economics per finance tests. Mandatory concession fields on multiyear bends, milestones, ramps, and PS splits feed forecast roll-forward and cohort math instead of strategic hand-waving. Lagging metrics sit beside segment and vintage coverage plus billings drift, deferred buildup, and payment-delay proxies. Packaging versus implementation breaks join CFO ceilings and net-new floors as hard stops before elephant sizing despite fat pipeline.",
4: "Success backs tying attainment to real economics so inflated ACV does not strand teams fixing live backlog. Vintage cohort stitching tests renewal and expansion claims when billings drift or collections stretch versus onboarding milestones—early warnings of downgrade from promised versus delivered value. Marketing bundles implying timelines or depth beyond realistic specialist and CSM concurrency must load delivery cost into margin gates. Operational gates: hiring keyed to start dates, tier readiness rules, caps on simultaneous giants, and trimming forecasted expansion when delivery or first-value timelines breach.",
5: "Sales leadership anchors exec commits to finance-grade win criteria so plans avoid signature theater. RevOps bridge and concession fields must ship before territories and quotas redraw or metrics only polish weak foundations. Success limits on concurrent elephants plus SLA-linked expansion cuts mirror how comp should behave alongside explicit net-new floors and carved new-logo capacity. Product marketing must spotlight where narrative promises timelines or depth implementation cannot meet—that mismatch drives discount, multiyear, and cycle risk more than slide ACV.",
6: "Product marketing pins the fracture: enterprise SKU sounds productized for integrations and governance while much work stays bespoke configuration and change management pods cannot absorb within wave limits. Collapsed headlines with underspecified services invite concessions instead of priced modules and gated milestones. Margin and cohort gates need per-tier sold-versus-delivered checklists covering integrations, data readiness, ownership, and first outcome timing. Elephant pursuit pauses unless SKU docs, quoting maps, and customer-ready bars align so staffing honors pods and waves without stealing net-new capacity.",
7: "Finance wants checklist discipline inside quoting so implementation risk stops hiding inside unstructured discounts and contract bends. Each item must translate into recognition triggers, invoice milestones, and delivery-loaded COGS—not narrative alignment alone. Without mechanical mapping, leaders cheer packaging while billings drift and margin eats custom work. Blocking elephant quotas stands until margin floors, discount and term ceilings, and cohort billings plus payment-delay prints clear the same vintage hurdle.",
8: "Success agrees checklists protect only when rows map to recognition timing, invoices, and loaded delivery cost—otherwise backlog hides bespoke labor. Hero positioning can accelerate buyer outcome expectations before readiness and integration prerequisites that already cap waves are satisfied. Items must be mandatory quoting prerequisites tied to start dates. Expansion stays conditional until delivery and first-outcome SLAs go green against those mappings rather than getting smoothed forward.",
9: "Product marketing agrees checklist lines belong in quoting as prerequisites, priced paths, or milestone premiums so concessions and cohort analytics mirror selling reality. Hero tone worsens readiness gaps, yet durable fixes are clearer SKUs and journeys with scored readiness and integration scope pre-signature so discounts reflect priced or declined gaps—not imagination financed later. Mapped economics plus non-ambiguous bundles aim to repeat larger ACVs without trading net-new pipeline for delivery debt.",
10: "RevOps will block attainment paths until each checklist item is a prerequisite or priced branch in quoting—readiness and integration cannot remain slide-only. Config maps need governance and elephant pursuit should halt when cohort coverage, billings drift, or vintage payment proxies miss thresholds beside lagging funnel stats. Caveat: lists fail without slip buckets, stage-age hygiene, and automatic expansion trims when first-outcome SLAs breach mapped milestones—otherwise forecasts quietly inherit delivery debt.",
11: "Sales accepts elephant quotas only when checklist atoms tie to recognition triggers, billing cadence, and delivery-loaded COGS crossing finance floors, ceilings, and vintage bars. Enforcement hinges on blocking premature wins, aging slip buckets, and SLA-driven expansion trims so clarity becomes rampable forecasts. Readiness scores and integration scope embed in quoting and attainment so headline ACV cannot outrun pods and waves. Net-new floors and carved capacity stay explicit so enterprise pushes do not silently sacrifice new logos.",
12: "Finance demands explicit cash modeling because multiyear and milestone billing can look fine for revenue while working capital stretches from stacked credits, usage true-ups, or long terms. Roll-forwards must reconcile bookings to billings, deferred movement, and collections by segment and vintage or enforcement stays cosmetic. Readiness fields need paired COGS loads on priced or declined gaps so incentives do not erode unit economics under heavier specialists and success labor. Net-new protections must survive final quota, territory, and accelerator design or tooling cleanliness still swaps volume for elongated cash and debt.",
}
for k,v in sorted(turns.items()):
    print(k, len(v), "OK" if len(v)<=400 else "TOO LONG")
